import { createSlice } from "@reduxjs/toolkit";

const initialState = [
  { name: "Pad",
    url: "/src/assets/items/sets/pad/pad-helm.webp",
    class: ["Dark Wizard"],
    defense: 18,
    defenseDefault: 18,
    update: 0,
    type: "Helm",
    typeLife: "typeDefense",
    optionType: "excellentOptions",
    ancient: ["Barnake", "Apollo"],
  },
  { name: "Vine",
    url: "/src/assets/items/sets/vine/vine-helm.webp",
    class: ["Fairy Elf"],
    defense: 17,
    defenseDefault: 17,
    update: 0,
    type: "Helm",
    typeLife: "typeDefense",
    optionType: "excellentOptions",
    ancient: [],
  },
  { name: "Slayer Red Wing",
    url: "/src/assets/items/sets/slayer red wing/Slayer Red Wing-helm.webp",
    class: ["Slayer"],
    defense: 18,
    defenseDefault: 18,
    update: 0,
    type: "Helm",
    typeLife: "typeDefense",
    optionType: "excellentOptions",
    ancient: [],
  },
  { name: "Rune Pad",
    url: "/src/assets/items/sets/rune pad/Rune Pad-helm.webp",
    class: ["Slayer"],
    defense: 20,
    defenseDefault: 20,
    update: 0,
    type: "Helm",
    typeLife: "typeDefense",
    optionType: "excellentOptions",
    ancient: [],
  },
  { name: "Leather",
  url: "/src/assets/items/sets/leather/leather-helm.webp",
  class: ["Dark Knight","Dark Lord","Rage Fighter"],
  defense: 20,
  defenseDefault: 20,
  update: 0,
  type: "Helm",
  typeLife: "typeDefense",
  optionType: "excellentOptions",
  ancient: [],
  },
  { name: "Magic Pad",
  url: "/src/assets/items/sets/Magic Pad/Magic Pad-helm.webp",
  class: ["Mage"],
  defense: 22,
  defenseDefault: 22,
  update: 0,
  type: "Helm",
  typeLife: "typeDefense",
  optionType: "excellentOptions",
  ancient: [],
  },
  { name: "Silk",
  url: "/src/assets/items/sets/Silk/Silk-helm.webp",
  class: ["Fairy Elf"],
  defense: 21,
  defenseDefault: 21,
  update: 0,
  type: "Helm",
  typeLife: "typeDefense",
  optionType: "excellentOptions",
  ancient: [],
  },
  { name: "Bronze",
  url: "/src/assets/items/sets/Bronze/Bronze-helm.webp",
  class: ["Dark Knight","Dark Lord"],
  defense: 22,
  defenseDefault: 22,
  update: 0,
  type: "Helm",
  typeLife: "typeDefense",
  optionType: "excellentOptions",
  ancient: [],
  },
  { name: "Bronze",
  url: "/src/assets/items/sets/Bronze/Bronze-helm.webp",
  class: ["Dark Knight","Dark Lord"],
  defense: 22,
  defenseDefault: 22,
  update: 0,
  type: "Helm",
  typeLife: "typeDefense",
  optionType: "excellentOptions",
  ancient: [],
  },

];
const helm = createSlice({
  name: "helm",
  initialState,
  reducers: {},
});

export default helm.reducer;
