import { createSlice } from "@reduxjs/toolkit";

const initialState = [
  { name: "Pad",
    url: "/src/assets/items/sets/pad/pad-helm.webp",
    class: ["Dark Wizard"],
    defense: 18,
    defenseDefault: 18,
    update: 0,
    type: "Helm",
    typeLife: "typeDefense",
    optionType: "excellentOptions",
    ancient: ["Barnake", "Apollo"],
  },
  { name: "Vine",
    url: "/src/assets/items/sets/vine/vine-helm.webp",
    class: ["Fairy Elf"],
    defense: 17,
    defenseDefault: 17,
    update: 0,
    type: "Helm",
    typeLife: "typeDefense",
    optionType: "excellentOptions",
    ancient: [],
  },
  { name: "Slayer Red Wing",
    url: "/src/assets/items/sets/Slayer Red Wing/Slayer Red Wing-helm.webp",
    class: ["Slayer"],
    defense: 18,
    defenseDefault: 18,
    update: 0,
    type: "Helm",
    typeLife: "typeDefense",
    optionType: "excellentOptions",
    ancient: [],
  },
  { name: "Rune Pad",
    url: "/src/assets/items/sets/Rune Pad/Rune Pad-helm.webp",
    class: ["Slayer"],
    defense: 20,
    defenseDefault: 20,
    update: 0,
    type: "Helm",
    typeLife: "typeDefense",
    optionType: "excellentOptions",
    ancient: [],
  },
  { name: "Rune Pad",
  url: "/src/assets/items/sets/Rune Pad/Rune Pad-helm.webp",
  class: ["Slayer"],
  defense: 20,
  defenseDefault: 20,
  update: 0,
  type: "Helm",
  typeLife: "typeDefense",
  optionType: "excellentOptions",
  ancient: [],
},
];
const helm = createSlice({
  name: "helm",
  initialState,
  reducers: {},
});

export default helm.reducer;
