import { createSlice } from "@reduxjs/toolkit";

const initialState = [
  {
    name: "Wings of Heaven",
    url: "/src/assets/items/wings/1/wings-of-heaven.webp",
    class: ["Dark Wizard", "Magic Gladiator", "Rage Fighter", "Rune Mage", "Gun Crusher", "Mage"],
    defense: 10,
    damageAbsorb: 12,
    DamageIncreaseRate: 12,
    minLevel: 150,
    defenseDefault: 10,
    damageAbsorbDefault: 12,
    DamageIncreaseRateDefault: 12,
    minLevelDefault: 150,
    update: 0,
    type: "wings",
    typeLife: "typeMagic",
    optionType: "wingsOption",
    tier: 1,
  },
  {
    name: "Wings of Satan",
    url: "/src/assets/items/wings/1/wings-of-satan.webp",
    class: ["Dark Knight", "Magic Gladiator", "Slayer"],
    defense: 20,
    damageAbsorb: 12,
    DamageIncreaseRate: 12,
    minLevel: 150,
    defenseDefault: 20,
    damageAbsorbDefault: 12,
    DamageIncreaseRateDefault: 12,
    minLevelDefault: 150,
    update: 0,
    type: "wings",
    typeLife: "typePhysical",
    optionType: "wingsOption",
    tier: 1,
  },
  {
    name: "Wings of Elf",
    url: "/src/assets/items/wings/1/wings-of-elf.webp",
    class: ["Fairy Elf"],
    defense: 10,
    damageAbsorb: 12,
    DamageIncreaseRate: 12,
    minLevel: 150,
    defenseDefault: 10,
    damageAbsorbDefault: 12,
    DamageIncreaseRateDefault: 12,
    minLevelDefault: 150,
    update: 0,
    type: "wings",
    typeLife: "typePhysical",
    optionType: "wingsOption",
    tier: 1,
  },
  {
    name: "Wing of Curse",
    url: "/src/assets/items/wings/1/wing-of-curse.webp",
    class: ["Summoner", "Dark Lord", "Grow Lancer"],
    defense: 10,
    damageAbsorb: 12,
    DamageIncreaseRate: 12,
    minLevel: 150,
    defenseDefault: 10,
    damageAbsorbDefault: 12,
    DamageIncreaseRateDefault: 12,
    minLevelDefault: 150,
    update: 0,
    type: "wings",
    typeLife: "typeCurse",
    optionType: "wingsOption",
    tier: 1,
  },
  {
    name: "Pure White Cloak",
    url: "/src/assets/items/wings/1/pure-white-cloak.webp",
    class: ["White Wizard"],
    defense: 10,
    damageAbsorb: 12,
    DamageIncreaseRate: 12,
    minLevel: 150,
    defenseDefault: 10,
    damageAbsorbDefault: 12,
    DamageIncreaseRateDefault: 12,
    minLevelDefault: 150,
    update: 0,
    type: "wings",
    typeLife: "typeMagic",
    optionType: "wingsOption",
    tier: 1,
  },
  {
    name: "Cloak of Steel",
    url: "/src/assets/items/wings/1/cloak-of-steel.webp",
    class: ["Illusion Knight"],
    defense: 20,
    damageAbsorb: 12,
    DamageIncreaseRate: 12,
    minLevel: 150,
    defenseDefault: 10,
    damageAbsorbDefault: 12,
    DamageIncreaseRateDefault: 12,
    minLevelDefault: 150,
    update: 0,
    type: "wings",
    typeLife: "typePhysical",
    optionType: "wingsOption",
    tier: 1,
  },
  {
    name: "Wings of Soul",
    url: "/src/assets/items/wings/2/wings-of-soul.webp",
    class: ["Soul Master", "Gun Breaker", "Rune Spell Master", "Wo Mage"],
    defense: 30,
    damageAbsorb: 25,
    DamageIncreaseRate: 32,
    minLevel: 215,
    defenseDefault: 30,
    damageAbsorbDefault: 25,
    DamageIncreaseRateDefault: 32,
    minLevelDefault: 215,
    update: 0,
    type: "wings",
    typeLife: "typeMagic",
    optionType: "wingsOption",
    tier: 2,
  },
  {
    name: "Wings of Dragon",
    url: "/src/assets/items/wings/2/wings-of-dragon.webp",
    class: ["Blade Knight", "Royal Slayer"],
    defense: 45,
    damageAbsorb: 25,
    DamageIncreaseRate: 32,
    minLevel: 215,
    defenseDefault: 45,
    damageAbsorbDefault: 25,
    DamageIncreaseRateDefault: 32,
    minLevelDefault: 215,
    update: 0,
    type: "wings",
    typeLife: "typePhysical",
    optionType: "wingsOption",
    tier: 2,
  },
  {
    name: "Wings of Spirit",
    url: "/src/assets/items/wings/2/wings-of-spirit.webp",
    class: ["Muse Elf"],
    defense: 30,
    damageAbsorb: 25,
    DamageIncreaseRate: 32,
    minLevel: 215,
    defenseDefault: 30,
    damageAbsorbDefault: 25,
    DamageIncreaseRateDefault: 32,
    minLevelDefault: 215,
    update: 0,
    type: "wings",
    typeLife: "typePhysical",
    optionType: "wingsOption",
    tier: 2,
  },
  {
    name: "Wings of Darkness",
    url: "/src/assets/items/wings/2/wings-of-darkness.webp",
    class: ["Magic Gladiator"],
    defense: 40,
    damageAbsorb: 25,
    DamageIncreaseRate: 32,
    minLevel: 215,
    defenseDefault: 40,
    damageAbsorbDefault: 25,
    DamageIncreaseRateDefault: 32,
    minLevelDefault: 215,
    update: 0,
    type: "wings",
    typeLife: "typePhysicalMagic",
    optionType: "wingsOption",
    tier: 2,
  },
  {
    name: "Cape of Lord",
    url: "/src/assets/items/wings/2/cape-of-lord.webp",
    class: ["Dark Lord"],
    defense: 15,
    damageAbsorb: 10,
    DamageIncreaseRate: 20,
    minLevel: 215,
    defenseDefault: 15,
    damageAbsorbDefault: 10,
    DamageIncreaseRateDefault: 20,
    minLevelDefault: 215,
    update: 0,
    type: "wings",
    typeLife: "typePhysical",
    optionType: "wingsOption",
    tier: 2,
  },
  {
    name: "Wing of Despair",
    url: "/src/assets/items/wings/2/wing-of-despair.webp",
    class: ["Bloody Summoner"],
    defense: 30,
    damageAbsorb: 25,
    DamageIncreaseRate: 32,
    minLevel: 215,
    defenseDefault: 30,
    damageAbsorbDefault: 25,
    DamageIncreaseRateDefault: 32,
    minLevelDefault: 215,
    update: 0,
    type: "wings",
    typeLife: "typeCurse",
    optionType: "wingsOption",
    tier: 2,
  },
  {
    name: "Cape of Fighter",
    url: "/src/assets/items/wings/2/cape-of-fighter.webp",
    class: ["Rage Fighter"],
    defense: 15,
    damageAbsorb: 10,
    DamageIncreaseRate: 20,
    minLevel: 215,
    defenseDefault: 15,
    damageAbsorbDefault: 10,
    DamageIncreaseRateDefault: 20,
    minLevelDefault: 215,
    update: 0,
    type: "wings",
    typeLife: "typePhysical",
    optionType: "wingsOption",
    tier: 2,
  },
  {
    name: "Cloak of Limit",
    url: "/src/assets/items/wings/2/cloak-of-limit.webp",
    class: ["Grow Lancer"],
    defense: 15,
    damageAbsorb: 20,
    DamageIncreaseRate: 20,
    minLevel: 215,
    defenseDefault: 15,
    damageAbsorbDefault: 20,
    DamageIncreaseRateDefault: 20,
    minLevelDefault: 215,
    update: 0,
    type: "wings",
    typeLife: "typePhysical",
    optionType: "wingsOption",
    tier: 2,
  },
  {
    name: "Cloak of Innoncence",
    url: "/src/assets/items/wings/2/cloak-of-innoncence.webp",
    class: ["Light Master"],
    defense: 30,
    damageAbsorb: 25,
    DamageIncreaseRate: 32,
    minLevel: 215,
    defenseDefault: 30,
    damageAbsorbDefault: 25,
    DamageIncreaseRateDefault: 32,
    minLevelDefault: 215,
    update: 0,
    type: "wings",
    typeLife: "typeMagic",
    optionType: "wingsOption",
    tier: 2,
  },
  {
    name: "Pitch Black Cloak",
    url: "/src/assets/items/wings/2/pitch-black-cloak.webp",
    class: ["Mirage Knight"],
    defense: 45,
    damageAbsorb: 25,
    DamageIncreaseRate: 32,
    minLevel: 215,
    defenseDefault: 45,
    damageAbsorbDefault: 25,
    DamageIncreaseRateDefault: 32,
    minLevelDefault: 215,
    update: 0,
    type: "wings",
    typeLife: "typePhysical",
    optionType: "wingsOption",
    tier: 2,
  },
  {
    name: "Wings of Chaos",
    url: "/src/assets/items/wings/2.5/wings-of-chaos.webp",
    class: ["Blde Knight", "Magic Gladiator", "Royal Slayer"],
    defense: 46,
    damageAbsorb: 30,
    DamageIncreaseRate: 33,
    minLevel: 290,
    defenseDefault: 46,
    damageAbsorbDefault: 30,
    DamageIncreaseRateDefault: 33,
    minLevelDefault: 290,
    update: 0,
    type: "wings",
    typeLife: "typePhysical",
    optionType: "wingsOption",
    tier: 2.5,
    options: [
      { update: true, defense: 3, damageAbsorb: 2, DamageIncreaseRate: 1 },
      { Luck: true },
      { life: true, typeOne: "HP recovery", typeThree: "Additional Dmg" },
    ],
  },
  {
    name: "Wings of Magic",
    url: "/src/assets/items/wings/2.5/wings-of-magic.webp",
    class: [
      "Soul Master",
      "Magic Gladiator",
      "Bloody Summoner",
      "Rune Spell Master",
      "Gun Breaker",
      "Wo Mage",
      "Light Master",
    ],
    defense: 37,
    damageAbsorb: 29,
    DamageIncreaseRate: 35,
    minLevel: 290,
    defenseDefault: 37,
    damageAbsorbDefault: 29,
    DamageIncreaseRateDefault: 35,
    minLevelDefault: 290,
    update: 0,
    type: "wings",
    typeLife: "typeCurse",
    optionType: "wingsOption",
    tier: 2.5,
    options: [
      { update: true, defense: 3, damageAbsorb: 2, DamageIncreaseRate: 1 },
      { Luck: true },
      { life: true, typeOne: "HP recovery", typeTwo: "Additional Wizardry Dmg", typeFour: "Additional Curse Spell" },
    ],
  },
  {
    name: "Wings of Life",
    url: "/src/assets/items/wings/2.5/wings-of-life.webp",
    class: ["Muse Elf"],
    defense: 37,
    damageAbsorb: 29,
    DamageIncreaseRate: 35,
    minLevel: 290,
    defenseDefault: 37,
    damageAbsorbDefault: 29,
    DamageIncreaseRateDefault: 35,
    minLevelDefault: 290,
    update: 0,
    type: "wings",
    typeLife: "typePhysical",
    optionType: "wingsOption",
    tier: 2.5,
    options: [
      { update: true, defense: 3, damageAbsorb: 2, DamageIncreaseRate: 1 },
      { Luck: true },
      { life: true, typeOne: "HP recovery", typeThree: "Additional Dmg" },
    ],
  },
  {
    name: "Cloak of Death",
    url: "/src/assets/items/wings/2.5/cloak-of-death.webp",
    class: ["Dark Lord", "Rage Fighter", "Grow Lancer"],
    defense: 27,
    damageAbsorb: 13,
    DamageIncreaseRate: 21,
    minLevel: 290,
    defenseDefault: 27,
    damageAbsorbDefault: 13,
    DamageIncreaseRateDefault: 21,
    minLevelDefault: 290,
    update: 0,
    type: "wings",
    typeLife: "typePhysical",
    optionType: "wingsOption",
    tier: 2.5,
    options: [
      { update: true, defense: 3, damageAbsorb: 2, DamageIncreaseRate: 1 },
      { Luck: true },
      { life: true, typeOne: "HP recovery", typeThree: "Additional Dmg" },
    ],
  },
  {
    name: "Wing of Eternal",
    url: "/src/assets/items/wings/3/wing-of-eternal.webp",
    class: ["Grand Master"],
    defense: 45,
    damageAbsorb: 39,
    DamageIncreaseRate: 39,
    minLevel: 400,
    defenseDefault: 45,
    damageAbsorbDefault: 39,
    DamageIncreaseRateDefault: 39,
    minLevelDefault: 400,
    update: 0,
    type: "wings",
    typeLife: "typeMagic",
    optionType: "wingsOption",
    tier: 3,
  },
  {
    name: "Wing of Storm",
    url: "/src/assets/items/wings/3/wing-of-storm.webp",
    class: ["Blade Master"],
    defense: 60,
    damageAbsorb: 39,
    DamageIncreaseRate: 39,
    minLevel: 400,
    defenseDefault: 60,
    damageAbsorbDefault: 39,
    DamageIncreaseRateDefault: 39,
    minLevelDefault: 400,
    update: 0,
    type: "wings",
    typeLife: "typePhysical",
    optionType: "wingsOption",
    tier: 3,
  },
  {
    name: "Wing of Illusion",
    url: "/src/assets/items/wings/3/wing-of-illusion.webp",
    class: ["High Elf"],
    defense: 45,
    damageAbsorb: 39,
    DamageIncreaseRate: 39,
    minLevel: 400,
    defenseDefault: 45,
    damageAbsorbDefault: 39,
    DamageIncreaseRateDefault: 39,
    minLevelDefault: 400,
    update: 0,
    type: "wings",
    typeLife: "typePhysical",
    optionType: "wingsOption",
    tier: 3,
  },
  {
    name: "Wing of Ruin",
    url: "/src/assets/items/wings/3/wings-of-ruin.webp",
    class: ["Duel Master"],
    defense: 55,
    damageAbsorb: 39,
    DamageIncreaseRate: 39,
    minLevel: 400,
    defenseDefault: 55,
    damageAbsorbDefault: 39,
    DamageIncreaseRateDefault: 39,
    minLevelDefault: 400,
    update: 0,
    type: "wings",
    typeLife: "typePhysicalMagic",
    optionType: "wingsOption",
    tier: 3,
  },
  {
    name: "Cape of Emperor",
    url: "/src/assets/items/wings/3/cape-of-emperor.webp",
    class: ["Lord Emperor"],
    defense: 45,
    damageAbsorb: 24,
    DamageIncreaseRate: 39,
    minLevel: 400,
    defenseDefault: 45,
    damageAbsorbDefault: 24,
    DamageIncreaseRateDefault: 39,
    minLevelDefault: 400,
    update: 0,
    type: "wings",
    typeLife: "typePhysical",
    optionType: "wingsOption",
    tier: 3,
  },
  {
    name: "Wing of Dimension",
    url: "/src/assets/items/wings/3/wing-of-dimension.webp",
    class: ["Dimension Master"],
    defense: 45,
    damageAbsorb: 39,
    DamageIncreaseRate: 39,
    minLevel: 400,
    defenseDefault: 45,
    damageAbsorbDefault: 39,
    DamageIncreaseRateDefault: 39,
    minLevelDefault: 400,
    update: 0,
    type: "wings",
    typeLife: "typeCurse",
    optionType: "wingsOption",
    tier: 3,
  },
  {
    name: "Cape of Overrule",
    url: "/src/assets/items/wings/3/cape-of-overrule.webp",
    class: ["Fist Master"],
    defense: 45,
    damageAbsorb: 39,
    DamageIncreaseRate: 39,
    minLevel: 400,
    defenseDefault: 45,
    damageAbsorbDefault: 39,
    DamageIncreaseRateDefault: 39,
    minLevelDefault: 400,
    update: 0,
    type: "wings",
    typeLife: "typePhysical",
    optionType: "wingsOption",
    tier: 3,
  },
  {
    name: "Cloak of Transcendence",
    url: "/src/assets/items/wings/3/cloak-of-transcendence.webp",
    class: ["Mirage Lancer"],
    defense: 45,
    damageAbsorb: 39,
    DamageIncreaseRate: 39,
    minLevel: 400,
    defenseDefault: 45,
    damageAbsorbDefault: 39,
    DamageIncreaseRateDefault: 39,
    minLevelDefault: 400,
    update: 0,
    type: "wings",
    typeLife: "typePhysical",
    optionType: "wingsOption",
    tier: 3,
  },
  {
    name: "Wings of Disillusion",
    url: "/src/assets/items/wings/3/wings-of-disillusion.webp",
    class: ["Rune Grand Masterr"],
    defense: 45,
    damageAbsorb: 39,
    DamageIncreaseRate: 39,
    minLevel: 400,
    defenseDefault: 45,
    damageAbsorbDefault: 39,
    DamageIncreaseRateDefault: 39,
    minLevelDefault: 400,
    update: 0,
    type: "wings",
    typeLife: "typeMagic",
    optionType: "wingsOption",
    tier: 3,
  },
  {
    name: "Wings of Silence",
    url: "/src/assets/items/wings/3/wings-of-silence.webp",
    class: ["Master Slayer"],
    defense: 45,
    damageAbsorb: 39,
    DamageIncreaseRate: 39,
    minLevel: 400,
    defenseDefault: 45,
    damageAbsorbDefault: 39,
    DamageIncreaseRateDefault: 39,
    minLevelDefault: 400,
    update: 0,
    type: "wings",
    typeLife: "typePhysical",
    optionType: "wingsOption",
    tier: 3,
  },
  {
    name: "Wings of Accuracy",
    url: "/src/assets/items/wings/3/wings-of-accuracy.webp",
    class: ["Master Gun Breaker"],
    defense: 45,
    damageAbsorb: 39,
    DamageIncreaseRate: 39,
    minLevel: 400,
    defenseDefault: 45,
    damageAbsorbDefault: 39,
    DamageIncreaseRateDefault: 39,
    minLevelDefault: 400,
    update: 0,
    type: "wings",
    typeLife: "typeMagic",
    optionType: "wingsOption",
    tier: 3,
  },
  {
    name: "Wings of Eternity",
    url: "/src/assets/items/wings/3/wings-of-eternity.webp",
    class: ["Rune Grand Masterr"],
    defense: 45,
    damageAbsorb: 39,
    DamageIncreaseRate: 39,
    minLevel: 400,
    defenseDefault: 45,
    damageAbsorbDefault: 39,
    DamageIncreaseRateDefault: 39,
    minLevelDefault: 400,
    update: 0,
    type: "wings",
    typeLife: "typeMagic",
    optionType: "wingsOption",
    tier: 3,
  },
  {
    name: "Cloak of Splendor",
    url: "/src/assets/items/wings/3/cloak-of-brilliance.webp",
    class: ["Shine Wizard"],
    defense: 45,
    damageAbsorb: 39,
    DamageIncreaseRate: 39,
    minLevel: 400,
    defenseDefault: 45,
    damageAbsorbDefault: 39,
    DamageIncreaseRateDefault: 39,
    minLevelDefault: 400,
    update: 0,
    type: "wings",
    typeLife: "typeMagic",
    optionType: "wingsOption",
    tier: 3,
  },
  {
    name: "Cloak of Death",
    url: "/src/assets/items/wings/3/cloak-of-death.webp",
    class: ["Ilussion Master"],
    defense: 45,
    damageAbsorb: 39,
    DamageIncreaseRate: 39,
    minLevel: 400,
    defenseDefault: 45,
    damageAbsorbDefault: 39,
    DamageIncreaseRateDefault: 39,
    minLevelDefault: 400,
    update: 0,
    type: "wings",
    typeLife: "typePhysical",
    optionType: "wingsOption",
    tier: 3,
  },
  {
    name: "Wings of Elysium",
    url: "/src/assets/items/wings/4/wings-of-elysium.webp",
    class: ["Soul Wizard"],
    damage: 100,
    defense: 140,
    damageAbsorb: 43,
    DamageIncreaseRate: 55,
    minLevel: 800,
    type: "wings",
    optionType: "wingsOption",
    tier: 4,
    options: [{ Luck: true }, { life: true, typeOne: "HP recovery", typeTwo: "Additional Wizardry Dmg" }],
  },
  {
    name: "Wings of Flame God",
    url: "/src/assets/items/wings/4/wings-of-flame-god.webp",
    class: ["Dragon Knight"],
    damage: 100,
    defense: 140,
    damageAbsorb: 43,
    DamageIncreaseRate: 55,
    minLevel: 800,
    type: "wings",
    optionType: "wingsOption",
    tier: 4,
    options: [{ Luck: true }, { life: true, typeOne: "HP recovery", typeThree: "Additional Dmg" }],
  },
  {
    name: "Wings of Celestial Body",
    url: "/src/assets/items/wings/4/wings-of-celestial-body.webp",
    class: ["Noble Elf"],
    damage: 100,
    defense: 140,
    damageAbsorb: 43,
    DamageIncreaseRate: 55,
    minLevel: 800,
    type: "wings",
    optionType: "wingsOption",
    tier: 4,
    options: [{ Luck: true }, { life: true, typeOne: "HP recovery", typeThree: "Additional Dmg" }],
  },
  {
    name: "Wings of Annihilation",
    url: "/src/assets/items/wings/4/wings-of-annihilation.webp",
    class: ["Magic Knight"],
    damage: 100,
    defense: 140,
    damageAbsorb: 43,
    DamageIncreaseRate: 55,
    minLevel: 800,
    type: "wings",
    optionType: "wingsOption",
    tier: 4,
    options: [
      { Luck: true },
      { life: true, typeOne: "HP recovery", typeTwo: "Additional Wizardry Dmg", typeThree: "Additional Dmg" },
    ],
  },
  {
    name: "Cloak of Dominator",
    url: "/src/assets/items/wings/4/cloak-of-dominator.webp",
    class: ["Emperor Lord"],
    damage: 100,
    defense: 140,
    damageAbsorb: 37,
    DamageIncreaseRate: 55,
    minLevel: 800,
    type: "wings",
    optionType: "wingsOption",
    tier: 4,
    options: [{ Luck: true }, { life: true, typeOne: "HP recovery", typeThree: "Additional Dmg" }],
  },
  {
    name: "Wings of Other World",
    url: "/src/assets/items/wings/4/wings-of-other-world.webp",
    class: ["Dimension Summoner"],
    damage: 100,
    defense: 140,
    damageAbsorb: 43,
    DamageIncreaseRate: 55,
    minLevel: 800,
    type: "wings",
    optionType: "wingsOption",
    tier: 4,
    options: [
      { Luck: true },
      { life: true, typeOne: "HP recovery", typeTwo: "Additional Wizardry Dmg", typeFour: "Additional Curse Spell" },
    ],
  },
  {
    name: "Cloak of Judgment",
    url: "/src/assets/items/wings/4/cloak-of-judgment.webp",
    class: ["Fist Blazer"],
    damage: 100,
    defense: 140,
    damageAbsorb: 43,
    DamageIncreaseRate: 55,
    minLevel: 800,
    type: "wings",
    optionType: "wingsOption",
    tier: 4,
    options: [{ Luck: true }, { life: true, typeOne: "HP recovery", typeThree: "Additional Dmg" }],
  },
  {
    name: "Cloak of Isolation",
    url: "/src/assets/items/wings/4/cloak-of-isolation.webp",
    class: ["Soul Lancer"],
    damage: 100,
    defense: 140,
    damageAbsorb: 43,
    DamageIncreaseRate: 55,
    minLevel: 800,
    type: "wings",
    optionType: "wingsOption",
    tier: 4,
    options: [{ Luck: true }, { life: true, typeOne: "HP recovery", typeThree: "Additional Dmg" }],
  },
  {
    name: "Wings of Fate",
    url: "/src/assets/items/wings/4/wings-of-fate.webp",
    class: ["Rune Wizard"],
    damage: 100,
    defense: 140,
    damageAbsorb: 43,
    DamageIncreaseRate: 55,
    minLevel: 800,
    type: "wings",
    optionType: "wingsOption",
    tier: 4,
    options: [{ Luck: true }, { life: true, typeOne: "HP recovery", typeTwo: "Additional Wizardry Dmg" }],
  },
  {
    name: "Wings of Bloodshed",
    url: "/src/assets/items/wings/4/wings-of-bloodshed.webp",
    class: ["Heist Gun Crusher"],
    damage: 100,
    defense: 140,
    damageAbsorb: 43,
    DamageIncreaseRate: 55,
    minLevel: 800,
    type: "wings",
    optionType: "wingsOption",
    tier: 4,
    options: [{ Luck: true }, { life: true, typeOne: "HP recovery", typeTwo: "Additional Wizardry Dmg" }],
  },
  {
    name: "Wings of Explosion",
    url: "/src/assets/items/wings/4/wings-of-explosion.webp",
    class: ["Mystic Mage"],
    damage: 100,
    defense: 140,
    damageAbsorb: 43,
    DamageIncreaseRate: 55,
    minLevel: 800,
    type: "wings",
    optionType: "wingsOption",
    tier: 4,
    options: [{ Luck: true }, { life: true, typeOne: "HP recovery", typeTwo: "Additional Wizardry Dmg" }],
  },
  {
    name: "Cloak of Radiance",
    url: "/src/assets/items/wings/4/cloak-of-radiance.webp",
    class: ["Shine Master"],
    damage: 100,
    defense: 140,
    damageAbsorb: 43,
    DamageIncreaseRate: 55,
    minLevel: 800,
    type: "wings",
    optionType: "wingsOption",
    tier: 4,
    options: [{ Luck: true }, { life: true, typeOne: "HP recovery", typeTwo: "Additional Wizardry Dmg" }],
  },
  {
    name: "Cloak of Hatred",
    url: "/src/assets/items/wings/4/cloak-of-hatred.webp",
    class: ["Illusion Master"],
    damage: 100,
    defense: 140,
    damageAbsorb: 43,
    DamageIncreaseRate: 55,
    minLevel: 800,
    type: "wings",
    optionType: "wingsOption",
    tier: 4,
    options: [{ Luck: true }, { life: true, typeOne: "HP recovery", typeThree: "Additional Dmg" }],
  },
  {
    name: "Wings of Conqueror",
    url: "/src/assets/items/wings/events/wings-of-conqueror.webp",
    class: [
      "Grand Master",
      "Blade Master",
      "High Elf",
      "Duel Master",
      "Lord Emperor",
      "Dimension Master",
      "Fist Master",
      "Mirage Lancer",
      "Rune Grand Master",
      "Master Slayer",
      "Master Gun Breaker",
      "Arch Mage",
      "Shine Wizard",
      "Ilussion Master",
    ],
    damage: 100,
    defense: 60,
    damageAbsorb: 39,
    DamageIncreaseRate: 39,
    minLevel: 400,
    type: "wings",
    optionType: "wingsOption",
    tier: "event",
  },
  {
    name: "Wing of Devil & Angel",
    url: "/src/assets/items/wings/events/wing-of-angel-and-devil.webp",
    class: [
      "Soul Master",
      "Blade Knight",
      "Muse Elf",
      "Magic Gladiator",
      "Dark Lord",
      "Bloody Summoner",
      "Rage Fighter",
      "Grow Lancer",
      "Rune Spell Master",
      "Royal Slayer",
      "Gun Breaker",
      "War Mage",
      "Light Master",
      "Mirage Knight",
    ],
    defense: 100,
    damageAbsorb: 75,
    DamageIncreaseRate: 75,
    minLevel: 350,
    type: "wings",
    optionType: "wingsOption",
    tier: "event",
    criticalDamageRate: 5,
    restoreAllLifeRate: 4,
    defenseIgnoreRate: 4,
    doubleDamageRate: 4,
  },
  {
    name: "Wings of Authority",
    url: "/src/assets/items/wings/events/wing-of-authority.webp",
    class: [
      "Grand Master",
      "Blade Master",
      "High Elf",
      "Duel Master",
      "Lord Emperor",
      "Dimension Master",
      "Fist Master",
      "Mirage Lancer",
      "Rune Grand Master",
      "Master Slayer",
      "Master Gun Breaker",
      "Arch Mage",
      "Shine Wizard",
      "Ilussion Master",
    ],
    damage: 300,
    defense: 700,
    damageAbsorb: 65,
    DamageIncreaseRate: 65,
    minLevel: 750,
    type: "wings",
    optionType: "wingsOption",
    tier: "event",
    criticalDamageRate: 5,
    restoreAllLifeRate: 6,
    defenseIgnoreRate: 6,
    doubleDamageRate: 6,
  },
];
const wings = createSlice({
  name: "wings",
  initialState,
  reducers: {},
});

export default wings.reducer;
